# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/coal/Desktop/Coding/C/cardboard

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/coal/Desktop/Coding/C/cardboard

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/coal/Desktop/Coding/C/cardboard/CMakeFiles /home/coal/Desktop/Coding/C/cardboard//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/coal/Desktop/Coding/C/cardboard/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named native_master

# Build rule for target.
native_master: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 native_master
.PHONY : native_master

# fast build rule for target.
native_master/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/build
.PHONY : native_master/fast

#=============================================================================
# Target rules for targets named native_server

# Build rule for target.
native_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 native_server
.PHONY : native_server

# fast build rule for target.
native_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/build
.PHONY : native_server/fast

#=============================================================================
# Target rules for targets named native_client

# Build rule for target.
native_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 native_client
.PHONY : native_client

# fast build rule for target.
native_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/build
.PHONY : native_client/fast

src/engine/3dgui.o: src/engine/3dgui.cpp.o
.PHONY : src/engine/3dgui.o

# target to build an object file
src/engine/3dgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/3dgui.cpp.o
.PHONY : src/engine/3dgui.cpp.o

src/engine/3dgui.i: src/engine/3dgui.cpp.i
.PHONY : src/engine/3dgui.i

# target to preprocess a source file
src/engine/3dgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/3dgui.cpp.i
.PHONY : src/engine/3dgui.cpp.i

src/engine/3dgui.s: src/engine/3dgui.cpp.s
.PHONY : src/engine/3dgui.s

# target to generate assembly for a file
src/engine/3dgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/3dgui.cpp.s
.PHONY : src/engine/3dgui.cpp.s

src/engine/bih.o: src/engine/bih.cpp.o
.PHONY : src/engine/bih.o

# target to build an object file
src/engine/bih.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/bih.cpp.o
.PHONY : src/engine/bih.cpp.o

src/engine/bih.i: src/engine/bih.cpp.i
.PHONY : src/engine/bih.i

# target to preprocess a source file
src/engine/bih.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/bih.cpp.i
.PHONY : src/engine/bih.cpp.i

src/engine/bih.s: src/engine/bih.cpp.s
.PHONY : src/engine/bih.s

# target to generate assembly for a file
src/engine/bih.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/bih.cpp.s
.PHONY : src/engine/bih.cpp.s

src/engine/blend.o: src/engine/blend.cpp.o
.PHONY : src/engine/blend.o

# target to build an object file
src/engine/blend.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/blend.cpp.o
.PHONY : src/engine/blend.cpp.o

src/engine/blend.i: src/engine/blend.cpp.i
.PHONY : src/engine/blend.i

# target to preprocess a source file
src/engine/blend.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/blend.cpp.i
.PHONY : src/engine/blend.cpp.i

src/engine/blend.s: src/engine/blend.cpp.s
.PHONY : src/engine/blend.s

# target to generate assembly for a file
src/engine/blend.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/blend.cpp.s
.PHONY : src/engine/blend.cpp.s

src/engine/blob.o: src/engine/blob.cpp.o
.PHONY : src/engine/blob.o

# target to build an object file
src/engine/blob.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/blob.cpp.o
.PHONY : src/engine/blob.cpp.o

src/engine/blob.i: src/engine/blob.cpp.i
.PHONY : src/engine/blob.i

# target to preprocess a source file
src/engine/blob.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/blob.cpp.i
.PHONY : src/engine/blob.cpp.i

src/engine/blob.s: src/engine/blob.cpp.s
.PHONY : src/engine/blob.s

# target to generate assembly for a file
src/engine/blob.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/blob.cpp.s
.PHONY : src/engine/blob.cpp.s

src/engine/client.o: src/engine/client.cpp.o
.PHONY : src/engine/client.o

# target to build an object file
src/engine/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/client.cpp.o
.PHONY : src/engine/client.cpp.o

src/engine/client.i: src/engine/client.cpp.i
.PHONY : src/engine/client.i

# target to preprocess a source file
src/engine/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/client.cpp.i
.PHONY : src/engine/client.cpp.i

src/engine/client.s: src/engine/client.cpp.s
.PHONY : src/engine/client.s

# target to generate assembly for a file
src/engine/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/client.cpp.s
.PHONY : src/engine/client.cpp.s

src/engine/command.o: src/engine/command.cpp.o
.PHONY : src/engine/command.o

# target to build an object file
src/engine/command.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/engine/command.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/engine/command.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/command.cpp.o
.PHONY : src/engine/command.cpp.o

src/engine/command.i: src/engine/command.cpp.i
.PHONY : src/engine/command.i

# target to preprocess a source file
src/engine/command.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/engine/command.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/engine/command.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/command.cpp.i
.PHONY : src/engine/command.cpp.i

src/engine/command.s: src/engine/command.cpp.s
.PHONY : src/engine/command.s

# target to generate assembly for a file
src/engine/command.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/engine/command.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/engine/command.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/command.cpp.s
.PHONY : src/engine/command.cpp.s

src/engine/console.o: src/engine/console.cpp.o
.PHONY : src/engine/console.o

# target to build an object file
src/engine/console.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/console.cpp.o
.PHONY : src/engine/console.cpp.o

src/engine/console.i: src/engine/console.cpp.i
.PHONY : src/engine/console.i

# target to preprocess a source file
src/engine/console.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/console.cpp.i
.PHONY : src/engine/console.cpp.i

src/engine/console.s: src/engine/console.cpp.s
.PHONY : src/engine/console.s

# target to generate assembly for a file
src/engine/console.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/console.cpp.s
.PHONY : src/engine/console.cpp.s

src/engine/decal.o: src/engine/decal.cpp.o
.PHONY : src/engine/decal.o

# target to build an object file
src/engine/decal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/decal.cpp.o
.PHONY : src/engine/decal.cpp.o

src/engine/decal.i: src/engine/decal.cpp.i
.PHONY : src/engine/decal.i

# target to preprocess a source file
src/engine/decal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/decal.cpp.i
.PHONY : src/engine/decal.cpp.i

src/engine/decal.s: src/engine/decal.cpp.s
.PHONY : src/engine/decal.s

# target to generate assembly for a file
src/engine/decal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/decal.cpp.s
.PHONY : src/engine/decal.cpp.s

src/engine/dynlight.o: src/engine/dynlight.cpp.o
.PHONY : src/engine/dynlight.o

# target to build an object file
src/engine/dynlight.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/dynlight.cpp.o
.PHONY : src/engine/dynlight.cpp.o

src/engine/dynlight.i: src/engine/dynlight.cpp.i
.PHONY : src/engine/dynlight.i

# target to preprocess a source file
src/engine/dynlight.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/dynlight.cpp.i
.PHONY : src/engine/dynlight.cpp.i

src/engine/dynlight.s: src/engine/dynlight.cpp.s
.PHONY : src/engine/dynlight.s

# target to generate assembly for a file
src/engine/dynlight.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/dynlight.cpp.s
.PHONY : src/engine/dynlight.cpp.s

src/engine/gamepad.o: src/engine/gamepad.cpp.o
.PHONY : src/engine/gamepad.o

# target to build an object file
src/engine/gamepad.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/gamepad.cpp.o
.PHONY : src/engine/gamepad.cpp.o

src/engine/gamepad.i: src/engine/gamepad.cpp.i
.PHONY : src/engine/gamepad.i

# target to preprocess a source file
src/engine/gamepad.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/gamepad.cpp.i
.PHONY : src/engine/gamepad.cpp.i

src/engine/gamepad.s: src/engine/gamepad.cpp.s
.PHONY : src/engine/gamepad.s

# target to generate assembly for a file
src/engine/gamepad.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/gamepad.cpp.s
.PHONY : src/engine/gamepad.cpp.s

src/engine/glare.o: src/engine/glare.cpp.o
.PHONY : src/engine/glare.o

# target to build an object file
src/engine/glare.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/glare.cpp.o
.PHONY : src/engine/glare.cpp.o

src/engine/glare.i: src/engine/glare.cpp.i
.PHONY : src/engine/glare.i

# target to preprocess a source file
src/engine/glare.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/glare.cpp.i
.PHONY : src/engine/glare.cpp.i

src/engine/glare.s: src/engine/glare.cpp.s
.PHONY : src/engine/glare.s

# target to generate assembly for a file
src/engine/glare.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/glare.cpp.s
.PHONY : src/engine/glare.cpp.s

src/engine/grass.o: src/engine/grass.cpp.o
.PHONY : src/engine/grass.o

# target to build an object file
src/engine/grass.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/grass.cpp.o
.PHONY : src/engine/grass.cpp.o

src/engine/grass.i: src/engine/grass.cpp.i
.PHONY : src/engine/grass.i

# target to preprocess a source file
src/engine/grass.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/grass.cpp.i
.PHONY : src/engine/grass.cpp.i

src/engine/grass.s: src/engine/grass.cpp.s
.PHONY : src/engine/grass.s

# target to generate assembly for a file
src/engine/grass.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/grass.cpp.s
.PHONY : src/engine/grass.cpp.s

src/engine/lightmap.o: src/engine/lightmap.cpp.o
.PHONY : src/engine/lightmap.o

# target to build an object file
src/engine/lightmap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/lightmap.cpp.o
.PHONY : src/engine/lightmap.cpp.o

src/engine/lightmap.i: src/engine/lightmap.cpp.i
.PHONY : src/engine/lightmap.i

# target to preprocess a source file
src/engine/lightmap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/lightmap.cpp.i
.PHONY : src/engine/lightmap.cpp.i

src/engine/lightmap.s: src/engine/lightmap.cpp.s
.PHONY : src/engine/lightmap.s

# target to generate assembly for a file
src/engine/lightmap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/lightmap.cpp.s
.PHONY : src/engine/lightmap.cpp.s

src/engine/main.o: src/engine/main.cpp.o
.PHONY : src/engine/main.o

# target to build an object file
src/engine/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/main.cpp.o
.PHONY : src/engine/main.cpp.o

src/engine/main.i: src/engine/main.cpp.i
.PHONY : src/engine/main.i

# target to preprocess a source file
src/engine/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/main.cpp.i
.PHONY : src/engine/main.cpp.i

src/engine/main.s: src/engine/main.cpp.s
.PHONY : src/engine/main.s

# target to generate assembly for a file
src/engine/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/main.cpp.s
.PHONY : src/engine/main.cpp.s

src/engine/master.o: src/engine/master.cpp.o
.PHONY : src/engine/master.o

# target to build an object file
src/engine/master.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/engine/master.cpp.o
.PHONY : src/engine/master.cpp.o

src/engine/master.i: src/engine/master.cpp.i
.PHONY : src/engine/master.i

# target to preprocess a source file
src/engine/master.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/engine/master.cpp.i
.PHONY : src/engine/master.cpp.i

src/engine/master.s: src/engine/master.cpp.s
.PHONY : src/engine/master.s

# target to generate assembly for a file
src/engine/master.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/engine/master.cpp.s
.PHONY : src/engine/master.cpp.s

src/engine/material.o: src/engine/material.cpp.o
.PHONY : src/engine/material.o

# target to build an object file
src/engine/material.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/material.cpp.o
.PHONY : src/engine/material.cpp.o

src/engine/material.i: src/engine/material.cpp.i
.PHONY : src/engine/material.i

# target to preprocess a source file
src/engine/material.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/material.cpp.i
.PHONY : src/engine/material.cpp.i

src/engine/material.s: src/engine/material.cpp.s
.PHONY : src/engine/material.s

# target to generate assembly for a file
src/engine/material.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/material.cpp.s
.PHONY : src/engine/material.cpp.s

src/engine/menus.o: src/engine/menus.cpp.o
.PHONY : src/engine/menus.o

# target to build an object file
src/engine/menus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/menus.cpp.o
.PHONY : src/engine/menus.cpp.o

src/engine/menus.i: src/engine/menus.cpp.i
.PHONY : src/engine/menus.i

# target to preprocess a source file
src/engine/menus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/menus.cpp.i
.PHONY : src/engine/menus.cpp.i

src/engine/menus.s: src/engine/menus.cpp.s
.PHONY : src/engine/menus.s

# target to generate assembly for a file
src/engine/menus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/menus.cpp.s
.PHONY : src/engine/menus.cpp.s

src/engine/normal.o: src/engine/normal.cpp.o
.PHONY : src/engine/normal.o

# target to build an object file
src/engine/normal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/normal.cpp.o
.PHONY : src/engine/normal.cpp.o

src/engine/normal.i: src/engine/normal.cpp.i
.PHONY : src/engine/normal.i

# target to preprocess a source file
src/engine/normal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/normal.cpp.i
.PHONY : src/engine/normal.cpp.i

src/engine/normal.s: src/engine/normal.cpp.s
.PHONY : src/engine/normal.s

# target to generate assembly for a file
src/engine/normal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/normal.cpp.s
.PHONY : src/engine/normal.cpp.s

src/engine/octa.o: src/engine/octa.cpp.o
.PHONY : src/engine/octa.o

# target to build an object file
src/engine/octa.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/octa.cpp.o
.PHONY : src/engine/octa.cpp.o

src/engine/octa.i: src/engine/octa.cpp.i
.PHONY : src/engine/octa.i

# target to preprocess a source file
src/engine/octa.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/octa.cpp.i
.PHONY : src/engine/octa.cpp.i

src/engine/octa.s: src/engine/octa.cpp.s
.PHONY : src/engine/octa.s

# target to generate assembly for a file
src/engine/octa.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/octa.cpp.s
.PHONY : src/engine/octa.cpp.s

src/engine/octaedit.o: src/engine/octaedit.cpp.o
.PHONY : src/engine/octaedit.o

# target to build an object file
src/engine/octaedit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/octaedit.cpp.o
.PHONY : src/engine/octaedit.cpp.o

src/engine/octaedit.i: src/engine/octaedit.cpp.i
.PHONY : src/engine/octaedit.i

# target to preprocess a source file
src/engine/octaedit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/octaedit.cpp.i
.PHONY : src/engine/octaedit.cpp.i

src/engine/octaedit.s: src/engine/octaedit.cpp.s
.PHONY : src/engine/octaedit.s

# target to generate assembly for a file
src/engine/octaedit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/octaedit.cpp.s
.PHONY : src/engine/octaedit.cpp.s

src/engine/octarender.o: src/engine/octarender.cpp.o
.PHONY : src/engine/octarender.o

# target to build an object file
src/engine/octarender.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/octarender.cpp.o
.PHONY : src/engine/octarender.cpp.o

src/engine/octarender.i: src/engine/octarender.cpp.i
.PHONY : src/engine/octarender.i

# target to preprocess a source file
src/engine/octarender.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/octarender.cpp.i
.PHONY : src/engine/octarender.cpp.i

src/engine/octarender.s: src/engine/octarender.cpp.s
.PHONY : src/engine/octarender.s

# target to generate assembly for a file
src/engine/octarender.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/octarender.cpp.s
.PHONY : src/engine/octarender.cpp.s

src/engine/physics.o: src/engine/physics.cpp.o
.PHONY : src/engine/physics.o

# target to build an object file
src/engine/physics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/physics.cpp.o
.PHONY : src/engine/physics.cpp.o

src/engine/physics.i: src/engine/physics.cpp.i
.PHONY : src/engine/physics.i

# target to preprocess a source file
src/engine/physics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/physics.cpp.i
.PHONY : src/engine/physics.cpp.i

src/engine/physics.s: src/engine/physics.cpp.s
.PHONY : src/engine/physics.s

# target to generate assembly for a file
src/engine/physics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/physics.cpp.s
.PHONY : src/engine/physics.cpp.s

src/engine/pvs.o: src/engine/pvs.cpp.o
.PHONY : src/engine/pvs.o

# target to build an object file
src/engine/pvs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/pvs.cpp.o
.PHONY : src/engine/pvs.cpp.o

src/engine/pvs.i: src/engine/pvs.cpp.i
.PHONY : src/engine/pvs.i

# target to preprocess a source file
src/engine/pvs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/pvs.cpp.i
.PHONY : src/engine/pvs.cpp.i

src/engine/pvs.s: src/engine/pvs.cpp.s
.PHONY : src/engine/pvs.s

# target to generate assembly for a file
src/engine/pvs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/pvs.cpp.s
.PHONY : src/engine/pvs.cpp.s

src/engine/raw.o: src/engine/raw.cpp.o
.PHONY : src/engine/raw.o

# target to build an object file
src/engine/raw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/raw.cpp.o
.PHONY : src/engine/raw.cpp.o

src/engine/raw.i: src/engine/raw.cpp.i
.PHONY : src/engine/raw.i

# target to preprocess a source file
src/engine/raw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/raw.cpp.i
.PHONY : src/engine/raw.cpp.i

src/engine/raw.s: src/engine/raw.cpp.s
.PHONY : src/engine/raw.s

# target to generate assembly for a file
src/engine/raw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/raw.cpp.s
.PHONY : src/engine/raw.cpp.s

src/engine/rendergl.o: src/engine/rendergl.cpp.o
.PHONY : src/engine/rendergl.o

# target to build an object file
src/engine/rendergl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/rendergl.cpp.o
.PHONY : src/engine/rendergl.cpp.o

src/engine/rendergl.i: src/engine/rendergl.cpp.i
.PHONY : src/engine/rendergl.i

# target to preprocess a source file
src/engine/rendergl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/rendergl.cpp.i
.PHONY : src/engine/rendergl.cpp.i

src/engine/rendergl.s: src/engine/rendergl.cpp.s
.PHONY : src/engine/rendergl.s

# target to generate assembly for a file
src/engine/rendergl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/rendergl.cpp.s
.PHONY : src/engine/rendergl.cpp.s

src/engine/rendermodel.o: src/engine/rendermodel.cpp.o
.PHONY : src/engine/rendermodel.o

# target to build an object file
src/engine/rendermodel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/rendermodel.cpp.o
.PHONY : src/engine/rendermodel.cpp.o

src/engine/rendermodel.i: src/engine/rendermodel.cpp.i
.PHONY : src/engine/rendermodel.i

# target to preprocess a source file
src/engine/rendermodel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/rendermodel.cpp.i
.PHONY : src/engine/rendermodel.cpp.i

src/engine/rendermodel.s: src/engine/rendermodel.cpp.s
.PHONY : src/engine/rendermodel.s

# target to generate assembly for a file
src/engine/rendermodel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/rendermodel.cpp.s
.PHONY : src/engine/rendermodel.cpp.s

src/engine/renderparticles.o: src/engine/renderparticles.cpp.o
.PHONY : src/engine/renderparticles.o

# target to build an object file
src/engine/renderparticles.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/renderparticles.cpp.o
.PHONY : src/engine/renderparticles.cpp.o

src/engine/renderparticles.i: src/engine/renderparticles.cpp.i
.PHONY : src/engine/renderparticles.i

# target to preprocess a source file
src/engine/renderparticles.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/renderparticles.cpp.i
.PHONY : src/engine/renderparticles.cpp.i

src/engine/renderparticles.s: src/engine/renderparticles.cpp.s
.PHONY : src/engine/renderparticles.s

# target to generate assembly for a file
src/engine/renderparticles.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/renderparticles.cpp.s
.PHONY : src/engine/renderparticles.cpp.s

src/engine/rendersky.o: src/engine/rendersky.cpp.o
.PHONY : src/engine/rendersky.o

# target to build an object file
src/engine/rendersky.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/rendersky.cpp.o
.PHONY : src/engine/rendersky.cpp.o

src/engine/rendersky.i: src/engine/rendersky.cpp.i
.PHONY : src/engine/rendersky.i

# target to preprocess a source file
src/engine/rendersky.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/rendersky.cpp.i
.PHONY : src/engine/rendersky.cpp.i

src/engine/rendersky.s: src/engine/rendersky.cpp.s
.PHONY : src/engine/rendersky.s

# target to generate assembly for a file
src/engine/rendersky.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/rendersky.cpp.s
.PHONY : src/engine/rendersky.cpp.s

src/engine/rendertext.o: src/engine/rendertext.cpp.o
.PHONY : src/engine/rendertext.o

# target to build an object file
src/engine/rendertext.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/rendertext.cpp.o
.PHONY : src/engine/rendertext.cpp.o

src/engine/rendertext.i: src/engine/rendertext.cpp.i
.PHONY : src/engine/rendertext.i

# target to preprocess a source file
src/engine/rendertext.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/rendertext.cpp.i
.PHONY : src/engine/rendertext.cpp.i

src/engine/rendertext.s: src/engine/rendertext.cpp.s
.PHONY : src/engine/rendertext.s

# target to generate assembly for a file
src/engine/rendertext.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/rendertext.cpp.s
.PHONY : src/engine/rendertext.cpp.s

src/engine/renderva.o: src/engine/renderva.cpp.o
.PHONY : src/engine/renderva.o

# target to build an object file
src/engine/renderva.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/renderva.cpp.o
.PHONY : src/engine/renderva.cpp.o

src/engine/renderva.i: src/engine/renderva.cpp.i
.PHONY : src/engine/renderva.i

# target to preprocess a source file
src/engine/renderva.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/renderva.cpp.i
.PHONY : src/engine/renderva.cpp.i

src/engine/renderva.s: src/engine/renderva.cpp.s
.PHONY : src/engine/renderva.s

# target to generate assembly for a file
src/engine/renderva.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/renderva.cpp.s
.PHONY : src/engine/renderva.cpp.s

src/engine/server.o: src/engine/server.cpp.o
.PHONY : src/engine/server.o

# target to build an object file
src/engine/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/engine/server.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/server.cpp.o
.PHONY : src/engine/server.cpp.o

src/engine/server.i: src/engine/server.cpp.i
.PHONY : src/engine/server.i

# target to preprocess a source file
src/engine/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/engine/server.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/server.cpp.i
.PHONY : src/engine/server.cpp.i

src/engine/server.s: src/engine/server.cpp.s
.PHONY : src/engine/server.s

# target to generate assembly for a file
src/engine/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/engine/server.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/server.cpp.s
.PHONY : src/engine/server.cpp.s

src/engine/serverbrowser.o: src/engine/serverbrowser.cpp.o
.PHONY : src/engine/serverbrowser.o

# target to build an object file
src/engine/serverbrowser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/serverbrowser.cpp.o
.PHONY : src/engine/serverbrowser.cpp.o

src/engine/serverbrowser.i: src/engine/serverbrowser.cpp.i
.PHONY : src/engine/serverbrowser.i

# target to preprocess a source file
src/engine/serverbrowser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/serverbrowser.cpp.i
.PHONY : src/engine/serverbrowser.cpp.i

src/engine/serverbrowser.s: src/engine/serverbrowser.cpp.s
.PHONY : src/engine/serverbrowser.s

# target to generate assembly for a file
src/engine/serverbrowser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/serverbrowser.cpp.s
.PHONY : src/engine/serverbrowser.cpp.s

src/engine/shader.o: src/engine/shader.cpp.o
.PHONY : src/engine/shader.o

# target to build an object file
src/engine/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/shader.cpp.o
.PHONY : src/engine/shader.cpp.o

src/engine/shader.i: src/engine/shader.cpp.i
.PHONY : src/engine/shader.i

# target to preprocess a source file
src/engine/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/shader.cpp.i
.PHONY : src/engine/shader.cpp.i

src/engine/shader.s: src/engine/shader.cpp.s
.PHONY : src/engine/shader.s

# target to generate assembly for a file
src/engine/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/shader.cpp.s
.PHONY : src/engine/shader.cpp.s

src/engine/shadowmap.o: src/engine/shadowmap.cpp.o
.PHONY : src/engine/shadowmap.o

# target to build an object file
src/engine/shadowmap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/shadowmap.cpp.o
.PHONY : src/engine/shadowmap.cpp.o

src/engine/shadowmap.i: src/engine/shadowmap.cpp.i
.PHONY : src/engine/shadowmap.i

# target to preprocess a source file
src/engine/shadowmap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/shadowmap.cpp.i
.PHONY : src/engine/shadowmap.cpp.i

src/engine/shadowmap.s: src/engine/shadowmap.cpp.s
.PHONY : src/engine/shadowmap.s

# target to generate assembly for a file
src/engine/shadowmap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/shadowmap.cpp.s
.PHONY : src/engine/shadowmap.cpp.s

src/engine/sound.o: src/engine/sound.cpp.o
.PHONY : src/engine/sound.o

# target to build an object file
src/engine/sound.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/sound.cpp.o
.PHONY : src/engine/sound.cpp.o

src/engine/sound.i: src/engine/sound.cpp.i
.PHONY : src/engine/sound.i

# target to preprocess a source file
src/engine/sound.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/sound.cpp.i
.PHONY : src/engine/sound.cpp.i

src/engine/sound.s: src/engine/sound.cpp.s
.PHONY : src/engine/sound.s

# target to generate assembly for a file
src/engine/sound.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/sound.cpp.s
.PHONY : src/engine/sound.cpp.s

src/engine/texture.o: src/engine/texture.cpp.o
.PHONY : src/engine/texture.o

# target to build an object file
src/engine/texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/texture.cpp.o
.PHONY : src/engine/texture.cpp.o

src/engine/texture.i: src/engine/texture.cpp.i
.PHONY : src/engine/texture.i

# target to preprocess a source file
src/engine/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/texture.cpp.i
.PHONY : src/engine/texture.cpp.i

src/engine/texture.s: src/engine/texture.cpp.s
.PHONY : src/engine/texture.s

# target to generate assembly for a file
src/engine/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/texture.cpp.s
.PHONY : src/engine/texture.cpp.s

src/engine/translate.o: src/engine/translate.cpp.o
.PHONY : src/engine/translate.o

# target to build an object file
src/engine/translate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/translate.cpp.o
.PHONY : src/engine/translate.cpp.o

src/engine/translate.i: src/engine/translate.cpp.i
.PHONY : src/engine/translate.i

# target to preprocess a source file
src/engine/translate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/translate.cpp.i
.PHONY : src/engine/translate.cpp.i

src/engine/translate.s: src/engine/translate.cpp.s
.PHONY : src/engine/translate.s

# target to generate assembly for a file
src/engine/translate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/translate.cpp.s
.PHONY : src/engine/translate.cpp.s

src/engine/water.o: src/engine/water.cpp.o
.PHONY : src/engine/water.o

# target to build an object file
src/engine/water.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/water.cpp.o
.PHONY : src/engine/water.cpp.o

src/engine/water.i: src/engine/water.cpp.i
.PHONY : src/engine/water.i

# target to preprocess a source file
src/engine/water.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/water.cpp.i
.PHONY : src/engine/water.cpp.i

src/engine/water.s: src/engine/water.cpp.s
.PHONY : src/engine/water.s

# target to generate assembly for a file
src/engine/water.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/water.cpp.s
.PHONY : src/engine/water.cpp.s

src/engine/world.o: src/engine/world.cpp.o
.PHONY : src/engine/world.o

# target to build an object file
src/engine/world.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/world.cpp.o
.PHONY : src/engine/world.cpp.o

src/engine/world.i: src/engine/world.cpp.i
.PHONY : src/engine/world.i

# target to preprocess a source file
src/engine/world.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/world.cpp.i
.PHONY : src/engine/world.cpp.i

src/engine/world.s: src/engine/world.cpp.s
.PHONY : src/engine/world.s

# target to generate assembly for a file
src/engine/world.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/world.cpp.s
.PHONY : src/engine/world.cpp.s

src/engine/worldio.o: src/engine/worldio.cpp.o
.PHONY : src/engine/worldio.o

# target to build an object file
src/engine/worldio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/engine/worldio.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/worldio.cpp.o
.PHONY : src/engine/worldio.cpp.o

src/engine/worldio.i: src/engine/worldio.cpp.i
.PHONY : src/engine/worldio.i

# target to preprocess a source file
src/engine/worldio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/engine/worldio.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/worldio.cpp.i
.PHONY : src/engine/worldio.cpp.i

src/engine/worldio.s: src/engine/worldio.cpp.s
.PHONY : src/engine/worldio.s

# target to generate assembly for a file
src/engine/worldio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/engine/worldio.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/engine/worldio.cpp.s
.PHONY : src/engine/worldio.cpp.s

src/fpsgame/ai.o: src/fpsgame/ai.cpp.o
.PHONY : src/fpsgame/ai.o

# target to build an object file
src/fpsgame/ai.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/ai.cpp.o
.PHONY : src/fpsgame/ai.cpp.o

src/fpsgame/ai.i: src/fpsgame/ai.cpp.i
.PHONY : src/fpsgame/ai.i

# target to preprocess a source file
src/fpsgame/ai.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/ai.cpp.i
.PHONY : src/fpsgame/ai.cpp.i

src/fpsgame/ai.s: src/fpsgame/ai.cpp.s
.PHONY : src/fpsgame/ai.s

# target to generate assembly for a file
src/fpsgame/ai.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/ai.cpp.s
.PHONY : src/fpsgame/ai.cpp.s

src/fpsgame/client.o: src/fpsgame/client.cpp.o
.PHONY : src/fpsgame/client.o

# target to build an object file
src/fpsgame/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/client.cpp.o
.PHONY : src/fpsgame/client.cpp.o

src/fpsgame/client.i: src/fpsgame/client.cpp.i
.PHONY : src/fpsgame/client.i

# target to preprocess a source file
src/fpsgame/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/client.cpp.i
.PHONY : src/fpsgame/client.cpp.i

src/fpsgame/client.s: src/fpsgame/client.cpp.s
.PHONY : src/fpsgame/client.s

# target to generate assembly for a file
src/fpsgame/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/client.cpp.s
.PHONY : src/fpsgame/client.cpp.s

src/fpsgame/discord.o: src/fpsgame/discord.cpp.o
.PHONY : src/fpsgame/discord.o

# target to build an object file
src/fpsgame/discord.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/discord.cpp.o
.PHONY : src/fpsgame/discord.cpp.o

src/fpsgame/discord.i: src/fpsgame/discord.cpp.i
.PHONY : src/fpsgame/discord.i

# target to preprocess a source file
src/fpsgame/discord.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/discord.cpp.i
.PHONY : src/fpsgame/discord.cpp.i

src/fpsgame/discord.s: src/fpsgame/discord.cpp.s
.PHONY : src/fpsgame/discord.s

# target to generate assembly for a file
src/fpsgame/discord.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/discord.cpp.s
.PHONY : src/fpsgame/discord.cpp.s

src/fpsgame/entities.o: src/fpsgame/entities.cpp.o
.PHONY : src/fpsgame/entities.o

# target to build an object file
src/fpsgame/entities.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/fpsgame/entities.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/entities.cpp.o
.PHONY : src/fpsgame/entities.cpp.o

src/fpsgame/entities.i: src/fpsgame/entities.cpp.i
.PHONY : src/fpsgame/entities.i

# target to preprocess a source file
src/fpsgame/entities.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/fpsgame/entities.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/entities.cpp.i
.PHONY : src/fpsgame/entities.cpp.i

src/fpsgame/entities.s: src/fpsgame/entities.cpp.s
.PHONY : src/fpsgame/entities.s

# target to generate assembly for a file
src/fpsgame/entities.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/fpsgame/entities.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/entities.cpp.s
.PHONY : src/fpsgame/entities.cpp.s

src/fpsgame/fps.o: src/fpsgame/fps.cpp.o
.PHONY : src/fpsgame/fps.o

# target to build an object file
src/fpsgame/fps.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/fps.cpp.o
.PHONY : src/fpsgame/fps.cpp.o

src/fpsgame/fps.i: src/fpsgame/fps.cpp.i
.PHONY : src/fpsgame/fps.i

# target to preprocess a source file
src/fpsgame/fps.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/fps.cpp.i
.PHONY : src/fpsgame/fps.cpp.i

src/fpsgame/fps.s: src/fpsgame/fps.cpp.s
.PHONY : src/fpsgame/fps.s

# target to generate assembly for a file
src/fpsgame/fps.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/fps.cpp.s
.PHONY : src/fpsgame/fps.cpp.s

src/fpsgame/fragmessages.o: src/fpsgame/fragmessages.cpp.o
.PHONY : src/fpsgame/fragmessages.o

# target to build an object file
src/fpsgame/fragmessages.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/fragmessages.cpp.o
.PHONY : src/fpsgame/fragmessages.cpp.o

src/fpsgame/fragmessages.i: src/fpsgame/fragmessages.cpp.i
.PHONY : src/fpsgame/fragmessages.i

# target to preprocess a source file
src/fpsgame/fragmessages.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/fragmessages.cpp.i
.PHONY : src/fpsgame/fragmessages.cpp.i

src/fpsgame/fragmessages.s: src/fpsgame/fragmessages.cpp.s
.PHONY : src/fpsgame/fragmessages.s

# target to generate assembly for a file
src/fpsgame/fragmessages.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/fragmessages.cpp.s
.PHONY : src/fpsgame/fragmessages.cpp.s

src/fpsgame/render.o: src/fpsgame/render.cpp.o
.PHONY : src/fpsgame/render.o

# target to build an object file
src/fpsgame/render.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/render.cpp.o
.PHONY : src/fpsgame/render.cpp.o

src/fpsgame/render.i: src/fpsgame/render.cpp.i
.PHONY : src/fpsgame/render.i

# target to preprocess a source file
src/fpsgame/render.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/render.cpp.i
.PHONY : src/fpsgame/render.cpp.i

src/fpsgame/render.s: src/fpsgame/render.cpp.s
.PHONY : src/fpsgame/render.s

# target to generate assembly for a file
src/fpsgame/render.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/render.cpp.s
.PHONY : src/fpsgame/render.cpp.s

src/fpsgame/scoreboard.o: src/fpsgame/scoreboard.cpp.o
.PHONY : src/fpsgame/scoreboard.o

# target to build an object file
src/fpsgame/scoreboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/scoreboard.cpp.o
.PHONY : src/fpsgame/scoreboard.cpp.o

src/fpsgame/scoreboard.i: src/fpsgame/scoreboard.cpp.i
.PHONY : src/fpsgame/scoreboard.i

# target to preprocess a source file
src/fpsgame/scoreboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/scoreboard.cpp.i
.PHONY : src/fpsgame/scoreboard.cpp.i

src/fpsgame/scoreboard.s: src/fpsgame/scoreboard.cpp.s
.PHONY : src/fpsgame/scoreboard.s

# target to generate assembly for a file
src/fpsgame/scoreboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/scoreboard.cpp.s
.PHONY : src/fpsgame/scoreboard.cpp.s

src/fpsgame/server.o: src/fpsgame/server.cpp.o
.PHONY : src/fpsgame/server.o

# target to build an object file
src/fpsgame/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/fpsgame/server.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/server.cpp.o
.PHONY : src/fpsgame/server.cpp.o

src/fpsgame/server.i: src/fpsgame/server.cpp.i
.PHONY : src/fpsgame/server.i

# target to preprocess a source file
src/fpsgame/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/fpsgame/server.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/server.cpp.i
.PHONY : src/fpsgame/server.cpp.i

src/fpsgame/server.s: src/fpsgame/server.cpp.s
.PHONY : src/fpsgame/server.s

# target to generate assembly for a file
src/fpsgame/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/fpsgame/server.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/server.cpp.s
.PHONY : src/fpsgame/server.cpp.s

src/fpsgame/waypoint.o: src/fpsgame/waypoint.cpp.o
.PHONY : src/fpsgame/waypoint.o

# target to build an object file
src/fpsgame/waypoint.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/waypoint.cpp.o
.PHONY : src/fpsgame/waypoint.cpp.o

src/fpsgame/waypoint.i: src/fpsgame/waypoint.cpp.i
.PHONY : src/fpsgame/waypoint.i

# target to preprocess a source file
src/fpsgame/waypoint.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/waypoint.cpp.i
.PHONY : src/fpsgame/waypoint.cpp.i

src/fpsgame/waypoint.s: src/fpsgame/waypoint.cpp.s
.PHONY : src/fpsgame/waypoint.s

# target to generate assembly for a file
src/fpsgame/waypoint.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/waypoint.cpp.s
.PHONY : src/fpsgame/waypoint.cpp.s

src/fpsgame/weapon.o: src/fpsgame/weapon.cpp.o
.PHONY : src/fpsgame/weapon.o

# target to build an object file
src/fpsgame/weapon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/weapon.cpp.o
.PHONY : src/fpsgame/weapon.cpp.o

src/fpsgame/weapon.i: src/fpsgame/weapon.cpp.i
.PHONY : src/fpsgame/weapon.i

# target to preprocess a source file
src/fpsgame/weapon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/weapon.cpp.i
.PHONY : src/fpsgame/weapon.cpp.i

src/fpsgame/weapon.s: src/fpsgame/weapon.cpp.s
.PHONY : src/fpsgame/weapon.s

# target to generate assembly for a file
src/fpsgame/weapon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/weapon.cpp.s
.PHONY : src/fpsgame/weapon.cpp.s

src/fpsgame/weaponstats.o: src/fpsgame/weaponstats.cpp.o
.PHONY : src/fpsgame/weaponstats.o

# target to build an object file
src/fpsgame/weaponstats.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/weaponstats.cpp.o
.PHONY : src/fpsgame/weaponstats.cpp.o

src/fpsgame/weaponstats.i: src/fpsgame/weaponstats.cpp.i
.PHONY : src/fpsgame/weaponstats.i

# target to preprocess a source file
src/fpsgame/weaponstats.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/weaponstats.cpp.i
.PHONY : src/fpsgame/weaponstats.cpp.i

src/fpsgame/weaponstats.s: src/fpsgame/weaponstats.cpp.s
.PHONY : src/fpsgame/weaponstats.s

# target to generate assembly for a file
src/fpsgame/weaponstats.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/fpsgame/weaponstats.cpp.s
.PHONY : src/fpsgame/weaponstats.cpp.s

src/shared/b64/buffer.o: src/shared/b64/buffer.c.o
.PHONY : src/shared/b64/buffer.o

# target to build an object file
src/shared/b64/buffer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/shared/b64/buffer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/shared/b64/buffer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/b64/buffer.c.o
.PHONY : src/shared/b64/buffer.c.o

src/shared/b64/buffer.i: src/shared/b64/buffer.c.i
.PHONY : src/shared/b64/buffer.i

# target to preprocess a source file
src/shared/b64/buffer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/shared/b64/buffer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/shared/b64/buffer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/b64/buffer.c.i
.PHONY : src/shared/b64/buffer.c.i

src/shared/b64/buffer.s: src/shared/b64/buffer.c.s
.PHONY : src/shared/b64/buffer.s

# target to generate assembly for a file
src/shared/b64/buffer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/shared/b64/buffer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/shared/b64/buffer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/b64/buffer.c.s
.PHONY : src/shared/b64/buffer.c.s

src/shared/b64/decode.o: src/shared/b64/decode.c.o
.PHONY : src/shared/b64/decode.o

# target to build an object file
src/shared/b64/decode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/shared/b64/decode.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/shared/b64/decode.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/b64/decode.c.o
.PHONY : src/shared/b64/decode.c.o

src/shared/b64/decode.i: src/shared/b64/decode.c.i
.PHONY : src/shared/b64/decode.i

# target to preprocess a source file
src/shared/b64/decode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/shared/b64/decode.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/shared/b64/decode.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/b64/decode.c.i
.PHONY : src/shared/b64/decode.c.i

src/shared/b64/decode.s: src/shared/b64/decode.c.s
.PHONY : src/shared/b64/decode.s

# target to generate assembly for a file
src/shared/b64/decode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/shared/b64/decode.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/shared/b64/decode.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/b64/decode.c.s
.PHONY : src/shared/b64/decode.c.s

src/shared/b64/encode.o: src/shared/b64/encode.c.o
.PHONY : src/shared/b64/encode.o

# target to build an object file
src/shared/b64/encode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/shared/b64/encode.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/shared/b64/encode.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/b64/encode.c.o
.PHONY : src/shared/b64/encode.c.o

src/shared/b64/encode.i: src/shared/b64/encode.c.i
.PHONY : src/shared/b64/encode.i

# target to preprocess a source file
src/shared/b64/encode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/shared/b64/encode.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/shared/b64/encode.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/b64/encode.c.i
.PHONY : src/shared/b64/encode.c.i

src/shared/b64/encode.s: src/shared/b64/encode.c.s
.PHONY : src/shared/b64/encode.s

# target to generate assembly for a file
src/shared/b64/encode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/shared/b64/encode.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/shared/b64/encode.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/b64/encode.c.s
.PHONY : src/shared/b64/encode.c.s

src/shared/cJSON.o: src/shared/cJSON.c.o
.PHONY : src/shared/cJSON.o

# target to build an object file
src/shared/cJSON.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/shared/cJSON.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/shared/cJSON.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/cJSON.c.o
.PHONY : src/shared/cJSON.c.o

src/shared/cJSON.i: src/shared/cJSON.c.i
.PHONY : src/shared/cJSON.i

# target to preprocess a source file
src/shared/cJSON.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/shared/cJSON.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/shared/cJSON.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/cJSON.c.i
.PHONY : src/shared/cJSON.c.i

src/shared/cJSON.s: src/shared/cJSON.c.s
.PHONY : src/shared/cJSON.s

# target to generate assembly for a file
src/shared/cJSON.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/shared/cJSON.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/shared/cJSON.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/cJSON.c.s
.PHONY : src/shared/cJSON.c.s

src/shared/crypto.o: src/shared/crypto.cpp.o
.PHONY : src/shared/crypto.o

# target to build an object file
src/shared/crypto.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/shared/crypto.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/shared/crypto.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/crypto.cpp.o
.PHONY : src/shared/crypto.cpp.o

src/shared/crypto.i: src/shared/crypto.cpp.i
.PHONY : src/shared/crypto.i

# target to preprocess a source file
src/shared/crypto.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/shared/crypto.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/shared/crypto.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/crypto.cpp.i
.PHONY : src/shared/crypto.cpp.i

src/shared/crypto.s: src/shared/crypto.cpp.s
.PHONY : src/shared/crypto.s

# target to generate assembly for a file
src/shared/crypto.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/shared/crypto.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/shared/crypto.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/crypto.cpp.s
.PHONY : src/shared/crypto.cpp.s

src/shared/geom.o: src/shared/geom.cpp.o
.PHONY : src/shared/geom.o

# target to build an object file
src/shared/geom.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/geom.cpp.o
.PHONY : src/shared/geom.cpp.o

src/shared/geom.i: src/shared/geom.cpp.i
.PHONY : src/shared/geom.i

# target to preprocess a source file
src/shared/geom.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/geom.cpp.i
.PHONY : src/shared/geom.cpp.i

src/shared/geom.s: src/shared/geom.cpp.s
.PHONY : src/shared/geom.s

# target to generate assembly for a file
src/shared/geom.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/geom.cpp.s
.PHONY : src/shared/geom.cpp.s

src/shared/glemu.o: src/shared/glemu.cpp.o
.PHONY : src/shared/glemu.o

# target to build an object file
src/shared/glemu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/glemu.cpp.o
.PHONY : src/shared/glemu.cpp.o

src/shared/glemu.i: src/shared/glemu.cpp.i
.PHONY : src/shared/glemu.i

# target to preprocess a source file
src/shared/glemu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/glemu.cpp.i
.PHONY : src/shared/glemu.cpp.i

src/shared/glemu.s: src/shared/glemu.cpp.s
.PHONY : src/shared/glemu.s

# target to generate assembly for a file
src/shared/glemu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/glemu.cpp.s
.PHONY : src/shared/glemu.cpp.s

src/shared/microtar.o: src/shared/microtar.c.o
.PHONY : src/shared/microtar.o

# target to build an object file
src/shared/microtar.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/shared/microtar.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/shared/microtar.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/microtar.c.o
.PHONY : src/shared/microtar.c.o

src/shared/microtar.i: src/shared/microtar.c.i
.PHONY : src/shared/microtar.i

# target to preprocess a source file
src/shared/microtar.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/shared/microtar.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/shared/microtar.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/microtar.c.i
.PHONY : src/shared/microtar.c.i

src/shared/microtar.s: src/shared/microtar.c.s
.PHONY : src/shared/microtar.s

# target to generate assembly for a file
src/shared/microtar.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/shared/microtar.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/shared/microtar.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/microtar.c.s
.PHONY : src/shared/microtar.c.s

src/shared/stream.o: src/shared/stream.cpp.o
.PHONY : src/shared/stream.o

# target to build an object file
src/shared/stream.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/shared/stream.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/shared/stream.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/stream.cpp.o
.PHONY : src/shared/stream.cpp.o

src/shared/stream.i: src/shared/stream.cpp.i
.PHONY : src/shared/stream.i

# target to preprocess a source file
src/shared/stream.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/shared/stream.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/shared/stream.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/stream.cpp.i
.PHONY : src/shared/stream.cpp.i

src/shared/stream.s: src/shared/stream.cpp.s
.PHONY : src/shared/stream.s

# target to generate assembly for a file
src/shared/stream.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/shared/stream.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/shared/stream.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/stream.cpp.s
.PHONY : src/shared/stream.cpp.s

src/shared/tools.o: src/shared/tools.cpp.o
.PHONY : src/shared/tools.o

# target to build an object file
src/shared/tools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/shared/tools.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/shared/tools.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/tools.cpp.o
.PHONY : src/shared/tools.cpp.o

src/shared/tools.i: src/shared/tools.cpp.i
.PHONY : src/shared/tools.i

# target to preprocess a source file
src/shared/tools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/shared/tools.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/shared/tools.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/tools.cpp.i
.PHONY : src/shared/tools.cpp.i

src/shared/tools.s: src/shared/tools.cpp.s
.PHONY : src/shared/tools.s

# target to generate assembly for a file
src/shared/tools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_master.dir/build.make CMakeFiles/native_master.dir/src/shared/tools.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_server.dir/build.make CMakeFiles/native_server.dir/src/shared/tools.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/tools.cpp.s
.PHONY : src/shared/tools.cpp.s

src/shared/zip.o: src/shared/zip.cpp.o
.PHONY : src/shared/zip.o

# target to build an object file
src/shared/zip.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/zip.cpp.o
.PHONY : src/shared/zip.cpp.o

src/shared/zip.i: src/shared/zip.cpp.i
.PHONY : src/shared/zip.i

# target to preprocess a source file
src/shared/zip.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/zip.cpp.i
.PHONY : src/shared/zip.cpp.i

src/shared/zip.s: src/shared/zip.cpp.s
.PHONY : src/shared/zip.s

# target to generate assembly for a file
src/shared/zip.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/native_client.dir/build.make CMakeFiles/native_client.dir/src/shared/zip.cpp.s
.PHONY : src/shared/zip.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... native_client"
	@echo "... native_master"
	@echo "... native_server"
	@echo "... src/engine/3dgui.o"
	@echo "... src/engine/3dgui.i"
	@echo "... src/engine/3dgui.s"
	@echo "... src/engine/bih.o"
	@echo "... src/engine/bih.i"
	@echo "... src/engine/bih.s"
	@echo "... src/engine/blend.o"
	@echo "... src/engine/blend.i"
	@echo "... src/engine/blend.s"
	@echo "... src/engine/blob.o"
	@echo "... src/engine/blob.i"
	@echo "... src/engine/blob.s"
	@echo "... src/engine/client.o"
	@echo "... src/engine/client.i"
	@echo "... src/engine/client.s"
	@echo "... src/engine/command.o"
	@echo "... src/engine/command.i"
	@echo "... src/engine/command.s"
	@echo "... src/engine/console.o"
	@echo "... src/engine/console.i"
	@echo "... src/engine/console.s"
	@echo "... src/engine/decal.o"
	@echo "... src/engine/decal.i"
	@echo "... src/engine/decal.s"
	@echo "... src/engine/dynlight.o"
	@echo "... src/engine/dynlight.i"
	@echo "... src/engine/dynlight.s"
	@echo "... src/engine/gamepad.o"
	@echo "... src/engine/gamepad.i"
	@echo "... src/engine/gamepad.s"
	@echo "... src/engine/glare.o"
	@echo "... src/engine/glare.i"
	@echo "... src/engine/glare.s"
	@echo "... src/engine/grass.o"
	@echo "... src/engine/grass.i"
	@echo "... src/engine/grass.s"
	@echo "... src/engine/lightmap.o"
	@echo "... src/engine/lightmap.i"
	@echo "... src/engine/lightmap.s"
	@echo "... src/engine/main.o"
	@echo "... src/engine/main.i"
	@echo "... src/engine/main.s"
	@echo "... src/engine/master.o"
	@echo "... src/engine/master.i"
	@echo "... src/engine/master.s"
	@echo "... src/engine/material.o"
	@echo "... src/engine/material.i"
	@echo "... src/engine/material.s"
	@echo "... src/engine/menus.o"
	@echo "... src/engine/menus.i"
	@echo "... src/engine/menus.s"
	@echo "... src/engine/normal.o"
	@echo "... src/engine/normal.i"
	@echo "... src/engine/normal.s"
	@echo "... src/engine/octa.o"
	@echo "... src/engine/octa.i"
	@echo "... src/engine/octa.s"
	@echo "... src/engine/octaedit.o"
	@echo "... src/engine/octaedit.i"
	@echo "... src/engine/octaedit.s"
	@echo "... src/engine/octarender.o"
	@echo "... src/engine/octarender.i"
	@echo "... src/engine/octarender.s"
	@echo "... src/engine/physics.o"
	@echo "... src/engine/physics.i"
	@echo "... src/engine/physics.s"
	@echo "... src/engine/pvs.o"
	@echo "... src/engine/pvs.i"
	@echo "... src/engine/pvs.s"
	@echo "... src/engine/raw.o"
	@echo "... src/engine/raw.i"
	@echo "... src/engine/raw.s"
	@echo "... src/engine/rendergl.o"
	@echo "... src/engine/rendergl.i"
	@echo "... src/engine/rendergl.s"
	@echo "... src/engine/rendermodel.o"
	@echo "... src/engine/rendermodel.i"
	@echo "... src/engine/rendermodel.s"
	@echo "... src/engine/renderparticles.o"
	@echo "... src/engine/renderparticles.i"
	@echo "... src/engine/renderparticles.s"
	@echo "... src/engine/rendersky.o"
	@echo "... src/engine/rendersky.i"
	@echo "... src/engine/rendersky.s"
	@echo "... src/engine/rendertext.o"
	@echo "... src/engine/rendertext.i"
	@echo "... src/engine/rendertext.s"
	@echo "... src/engine/renderva.o"
	@echo "... src/engine/renderva.i"
	@echo "... src/engine/renderva.s"
	@echo "... src/engine/server.o"
	@echo "... src/engine/server.i"
	@echo "... src/engine/server.s"
	@echo "... src/engine/serverbrowser.o"
	@echo "... src/engine/serverbrowser.i"
	@echo "... src/engine/serverbrowser.s"
	@echo "... src/engine/shader.o"
	@echo "... src/engine/shader.i"
	@echo "... src/engine/shader.s"
	@echo "... src/engine/shadowmap.o"
	@echo "... src/engine/shadowmap.i"
	@echo "... src/engine/shadowmap.s"
	@echo "... src/engine/sound.o"
	@echo "... src/engine/sound.i"
	@echo "... src/engine/sound.s"
	@echo "... src/engine/texture.o"
	@echo "... src/engine/texture.i"
	@echo "... src/engine/texture.s"
	@echo "... src/engine/translate.o"
	@echo "... src/engine/translate.i"
	@echo "... src/engine/translate.s"
	@echo "... src/engine/water.o"
	@echo "... src/engine/water.i"
	@echo "... src/engine/water.s"
	@echo "... src/engine/world.o"
	@echo "... src/engine/world.i"
	@echo "... src/engine/world.s"
	@echo "... src/engine/worldio.o"
	@echo "... src/engine/worldio.i"
	@echo "... src/engine/worldio.s"
	@echo "... src/fpsgame/ai.o"
	@echo "... src/fpsgame/ai.i"
	@echo "... src/fpsgame/ai.s"
	@echo "... src/fpsgame/client.o"
	@echo "... src/fpsgame/client.i"
	@echo "... src/fpsgame/client.s"
	@echo "... src/fpsgame/discord.o"
	@echo "... src/fpsgame/discord.i"
	@echo "... src/fpsgame/discord.s"
	@echo "... src/fpsgame/entities.o"
	@echo "... src/fpsgame/entities.i"
	@echo "... src/fpsgame/entities.s"
	@echo "... src/fpsgame/fps.o"
	@echo "... src/fpsgame/fps.i"
	@echo "... src/fpsgame/fps.s"
	@echo "... src/fpsgame/fragmessages.o"
	@echo "... src/fpsgame/fragmessages.i"
	@echo "... src/fpsgame/fragmessages.s"
	@echo "... src/fpsgame/render.o"
	@echo "... src/fpsgame/render.i"
	@echo "... src/fpsgame/render.s"
	@echo "... src/fpsgame/scoreboard.o"
	@echo "... src/fpsgame/scoreboard.i"
	@echo "... src/fpsgame/scoreboard.s"
	@echo "... src/fpsgame/server.o"
	@echo "... src/fpsgame/server.i"
	@echo "... src/fpsgame/server.s"
	@echo "... src/fpsgame/waypoint.o"
	@echo "... src/fpsgame/waypoint.i"
	@echo "... src/fpsgame/waypoint.s"
	@echo "... src/fpsgame/weapon.o"
	@echo "... src/fpsgame/weapon.i"
	@echo "... src/fpsgame/weapon.s"
	@echo "... src/fpsgame/weaponstats.o"
	@echo "... src/fpsgame/weaponstats.i"
	@echo "... src/fpsgame/weaponstats.s"
	@echo "... src/shared/b64/buffer.o"
	@echo "... src/shared/b64/buffer.i"
	@echo "... src/shared/b64/buffer.s"
	@echo "... src/shared/b64/decode.o"
	@echo "... src/shared/b64/decode.i"
	@echo "... src/shared/b64/decode.s"
	@echo "... src/shared/b64/encode.o"
	@echo "... src/shared/b64/encode.i"
	@echo "... src/shared/b64/encode.s"
	@echo "... src/shared/cJSON.o"
	@echo "... src/shared/cJSON.i"
	@echo "... src/shared/cJSON.s"
	@echo "... src/shared/crypto.o"
	@echo "... src/shared/crypto.i"
	@echo "... src/shared/crypto.s"
	@echo "... src/shared/geom.o"
	@echo "... src/shared/geom.i"
	@echo "... src/shared/geom.s"
	@echo "... src/shared/glemu.o"
	@echo "... src/shared/glemu.i"
	@echo "... src/shared/glemu.s"
	@echo "... src/shared/microtar.o"
	@echo "... src/shared/microtar.i"
	@echo "... src/shared/microtar.s"
	@echo "... src/shared/stream.o"
	@echo "... src/shared/stream.i"
	@echo "... src/shared/stream.s"
	@echo "... src/shared/tools.o"
	@echo "... src/shared/tools.i"
	@echo "... src/shared/tools.s"
	@echo "... src/shared/zip.o"
	@echo "... src/shared/zip.i"
	@echo "... src/shared/zip.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

